Repository aperoMoi/captcha-generate, pull requests merged in 2018-10, with the labels that each got.

#1 Create LICENSE
  LICENSE
Labels: administrative content

#4 Create PULL_REQUEST_TEMPLATE.md
  PULL_REQUEST_TEMPLATE.md
Labels: wiki

#3 Develop
  README.md
Labels: update

#6 Update README.md
  README.md
Labels: update

#8 ajout d'une fonctionnalité php de création de captcha
  GenerateCaptcha.php
  fonts/Kavivanar-Regular.ttf
  fonts/Oswald-Bold.ttf
  fonts/Oswald-Regular.ttf
  fonts/Raleway-Regular.ttf
  fonts/Raleway-SemiBoldItalic.ttf
  fonts/Roboto-Regular.ttf
  fonts/Roboto-Thin.ttf
  fonts/RobotoCondensed-Italic.ttf
  fonts/RobotoCondensed-LightItalic.ttf
  fonts/RobotoCondensed-Regular.ttf
  fonts/Skranji-Regular.ttf
Labels: update

#11 Travis CI
  .travis.yml
  GenerateCaptcha.php
Labels: update

#14 Update travis.yml for test
  .travis.yml
Labels: bug

#16 Configure docs
  docs/index.html
  index.html
Labels: update
